version: '3.9'
services:
  jupyter:
    image: rlourenc/iris-jupyter:latest
    hostname: jupyter
    container_name: jupyter
    entrypoint: jupyter lab --ip 0.0.0.0 --port 8888 --allow-root
    ports:
    - "4200:8888"
    - "4201:6006"
    volumes:
    - type: bind
      source: ./workspace
      target: /home/jovyan/workspace
  iris:
    image: rlourenc/iris-community:latest
    hostname: iris
    container_name: iris
    ports:
    - 9092:52773
